name: Deploy build to PyPI PROD

on:
  push:
    branches:
        - main
    paths:
        - 'prod/**' 
env:
  PYTHON_FILE_DIR: 'prod/aws_utils_lib-base'


jobs:
  deploy-library:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Building
        run: |          
          python3 setup.py sdist bdist_wheel --universal

        working-directory: ${{ env.PYTHON_FILE_DIR }}

      - name: Publish a Python distribution to PyPI}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          user: __token__
          password: ${{ secrets.PYPIPROD }}
          skip_existing: true
          packages_dir: ${{ env.PYTHON_FILE_DIR }}/dist

