name: Deploy build to PyPI

on:
  push:
    branches:
        - main
    paths:
        - 'test/**' #Directorio repo del PUSH / PR
env:
  PYTHON_FILE_DIR: 'test'


jobs:
  deploy-library:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Building
        run: |
          ls -l
          python3 setup.py sdist bdist_wheel
          ls -l
        working-directory: ${{ env.PYTHON_FILE_DIR }}

      - name: Publish a Python distribution to PyPI}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TESTPYPI }}
          repository_url: https://test.pypi.org/legacy/
          skip_existing: true
        run: ls -l
        working-directory: ${{ env.PYTHON_FILE_DIR }}
